"""Adição coluna Data nascimento

Revision ID: 23409bea1eee
Revises: b64f6c5550f2
Create Date: 2025-11-11 23:31:45.112211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23409bea1eee'
down_revision: Union[str, Sequence[str], None] = 'b64f6c5550f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('birthdate', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'birthdate')
    # ### end Alembic commands ###
